### ISSUE TITLE
format about dataset 

### ISSUE THREAD

**Issue by chenhaoenen** [taoqi98/PP-Rec#3]
Great work! I have some question about Dataset.
In UserContent.py, 
![image](https://user-images.githubusercontent.com/49124360/152763568-d223c1ee-2e33-4e90-bd40-172fcc538b9a.png)
In the function about load_session, As I understand it, sessions are built by reading the user's history of clicks, What do **pos** and **neg** stand for?  What is the list after split?  

=====================================
In addition, in preprocessing.py 
![image](https://user-images.githubusercontent.com/49124360/152764621-92aeec99-02fa-49f2-b553-ddbd069b2020.png)
multi clicks were split, but I cant understand what happend about **pos** and **neg**.
Can you give me an example of understanding?
Thanks!

**Comment by taoqi98** [comment]
Thank you for your attention to our work. In real-world news recommendation scenarios, user data are usually maintained in the impression format. Specifically, when a user browsing the online news platforms, the server will display some news (e.g. N) articles to the user. The user may be interested in part of the displayed news (e.g., K) and click them. In this case, these N news articles are displayed to the user at the same time, thus we say that these news articles are in the same news impression. During model training, we will select m negative samples (non-clicked news) for each positive sample (clicked news) from the same news impression. In our processing codes, the "sess" variable represents the news articles in the same impression, the "pos" variable represents the positive samples in this impression, and the "neg" variable represents the negative samples in this impression. Besides, you can refer to the format of the MIND data (https://msnews.github.io/) to understand this problem.

**Comment by chenhaoenen** [comment]
Thanks for the reply.
