### ISSUE TITLE
predict_generator function

### ISSUE THREAD

**Issue by igor17400** [taoqi98/PP-Rec#5]
Hi there,
I had the chance to review your paper, and I must say, it's truly captivating! 

While going through the general logic presented in the paper's accompanying Jupyter notebook, I noticed the usage of the `predict_generator` function. 

However, while examining the files, it appears that this function does not exist.

Could you kindly provide an explanation of how the `predict_generator` function works? More specifically for the following code line

```
news_scoring = news_encoder.predict_generator(news_generator,verbose=True)
```

Best regards.

**Comment by YiboZhao624** [comment]
news_encoder is a `keras.Model` returned by `create_pe_model` function in Encoders.py. In detail, the function `create_pe_model` called the `get_news_encoder`, which use the `keras.Model()` function to build a keras model. Then, by call the `predict_generator`, it will produce the result of predict.
More info about predict_generator, see https://tensorflow.rstudio.com/reference/keras/predict_generator

**Comment by igor17400** [comment]
@zhaoyib thanks!
